modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/amadornes/SuperCircuitMaker/issues"
displayURL="http://amadornes.com/"
logoFile="examplemod.png"
credits="Thanks to everyone for putting up with me"
authors="amadornes"
[[mods]]
modId="supercircuitmaker"
version="${file.jarVersion}"
displayName="Super Circuit Maker"
#updateJSONURL="http://myurl.me/"
description='''
Tiny circuits \o/
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,)"
    ordering="NONE"
    side="BOTH"